In [22]:
import numpy as np
import pandas as pd

In [ ]:
df = pd.read_csv("https://github.com/anvarnarz/praktikum_datasets/raw/main/automobile_data_nan.csv", index_col=0)
df

,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
index,,,,,,,,,
0,alfa-romero,convertible,88.6,168.8,dohc,four,NaN,21.0,13495.0
1,alfa-romero,convertible,NaN,168.8,dohc,four,111.0,21.0,16500.0
2,alfa-romero,hatchback,94.5,171.2,ohcv,six,154.0,NaN,16500.0
3,audi,sedan,99.8,176.6,ohc,four,102.0,24.0,13950.0
4,audi,sedan,99.4,176.6,ohc,five,NaN,NaN,17450.0
...,...,...,...,...,...,...,...,...,...
81,volkswagen,sedan,97.3,171.7,ohc,four,85.0,27.0,7975.0
82,volkswagen,sedan,NaN,171.7,NaN,four,52.0,37.0,7995.0
86,volkswagen,sedan,97.3,NaN,ohc,four,100.0,NaN,9995.0
87,volvo,sedan,104.3,188.8,NaN,four,114.0,23.0,12940.0
88,volvo,wagon,104.3,188.8,ohc,four,NaN,23.0,13415.0

In [ ]:
df.isnull().sum()

company              0
body-style           0
wheel-base          15
length              13
engine-type         12
num-of-cylinders     0
horsepower          16
average-mileage     15
price                3
dtype: int64

.dropna()

In [23]:
df.dropna()

,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
index,,,,,,,,,
3,audi,sedan,99.8,176.6,ohc,four,102.0,24.0,13950.0
5,audi,sedan,99.8,177.3,ohc,five,110.0,19.0,15250.0
6,audi,wagon,105.8,192.7,ohc,five,110.0,19.0,18920.0
17,chevrolet,hatchback,94.5,155.9,ohc,four,70.0,38.0,6295.0
19,dodge,hatchback,93.7,157.3,ohc,four,68.0,31.0,6377.0
28,honda,sedan,96.5,175.4,ohc,four,101.0,24.0,12945.0
34,jaguar,sedan,113.0,199.6,dohc,six,176.0,15.0,35550.0
37,mazda,hatchback,93.1,159.1,ohc,four,68.0,31.0,6095.0
38,mazda,hatchback,93.1,159.1,ohc,four,68.0,31.0,6795.0
54,nissan,sedan,94.5,165.3,ohc,four,69.0,31.0,6649.0
56,nissan,wagon,94.5,170.2,ohc,four,69.0,31.0,7349.0
62,porsche,convertible,89.5,168.9,ohcf,six,207.0,17.0,37028.0
69,toyota,wagon,95.7,169.7,ohc,four,62.0,31.0,6918.0
81,volkswagen,sedan,97.3,171.7,ohc,four,85.0,27.0,7975.0

In [ ]:
df.dropna(axis=1, thresh=48)

           company   body-style  length engine-type num-of-cylinders    price
index
0      alfa-romero  convertible   168.8        dohc             four  13495.0
1      alfa-romero  convertible   168.8        dohc             four  16500.0
2      alfa-romero    hatchback   171.2        ohcv              six  16500.0
3             audi        sedan   176.6         ohc             four  13950.0
4             audi        sedan   176.6         ohc             five  17450.0
...            ...          ...     ...         ...              ...      ...
81      volkswagen        sedan   171.7         ohc             four   7975.0
82      volkswagen        sedan   171.7         NaN             four   7995.0
86      volkswagen        sedan     NaN         ohc             four   9995.0
87           volvo        sedan   188.8         NaN             four  12940.0
88           volvo        wagon   188.8         ohc             four  13415.0

[61 rows x 6 columns]

In [ ]:
df.dropna(subset=['price','horsepower','average-mileage'], inplace=True)

In [ ]:
df

,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
index,,,,,,,,,
1,alfa-romero,convertible,NaN,168.8,dohc,four,111.0,21.0,16500.0
3,audi,sedan,99.8,176.6,ohc,four,102.0,24.0,13950.0
5,audi,sedan,99.8,177.3,ohc,five,110.0,19.0,15250.0
6,audi,wagon,105.8,192.7,ohc,five,110.0,19.0,18920.0
10,bmw,sedan,NaN,176.8,ohc,four,101.0,23.0,16925.0
14,bmw,sedan,103.5,NaN,ohc,six,182.0,16.0,41315.0
17,chevrolet,hatchback,94.5,155.9,ohc,four,70.0,38.0,6295.0
19,dodge,hatchback,93.7,157.3,ohc,four,68.0,31.0,6377.0
27,honda,wagon,96.5,NaN,ohc,four,76.0,30.0,7295.0
28,honda,sedan,96.5,175.4,ohc,four,101.0,24.0,12945.0
30,isuzu,sedan,NaN,170.7,ohc,four,78.0,24.0,6785.0
34,jaguar,sedan,113.0,199.6,dohc,six,176.0,15.0,35550.0
35,jaguar,sedan,NaN,191.7,ohcv,twelve,262.0,13.0,36000.0
37,mazda,hatchback,93.1,159.1,ohc,four,68.0,31.0,6095.0
38,mazda,hatchback,93.1,159.1,ohc,four,68.0,31.0,6795.0
39,mazda,hatchback,NaN,NaN,NaN,two,101.0,17.0,11845.0
44,mercedes-benz,sedan,110.0,190.9,NaN,five,123.0,22.0,25552.0
45,mercedes-benz,wagon,NaN,190.9,ohc,five,123.0,22.0,28248.0
46,mercedes-benz,sedan,120.9,208.1,NaN,eight,184.0,14.0,40960.0
47,mercedes-benz,hardtop,112.0,199.2,NaN,eight,184.0,14.0,45400.0
50,mitsubishi,hatchback,93.7,NaN,NaN,four,68.0,31.0,6189.0
54,nissan,sedan,94.5,165.3,ohc,four,69.0,31.0,6649.0
55,nissan,sedan,NaN,165.3,ohc,four,69.0,31.0,6849.0
56,nissan,wagon,94.5,170.2,ohc,four,69.0,31.0,7349.0
61,porsche,hardtop,NaN,NaN,NaN,six,207.0,17.0,34028.0
62,porsche,convertible,89.5,168.9,ohcf,six,207.0,17.0,37028.0
66,toyota,hatchback,NaN,158.7,ohc,four,62.0,35.0,5348.0
68,toyota,hatchback,NaN,158.7,ohc,four,62.0,31.0,6488.0
69,toyota,wagon,95.7,169.7,ohc,four,62.0,31.0,6918.0
70,toyota,wagon,95.7,NaN,NaN,four,62.0,27.0,7898.0
81,volkswagen,sedan,97.3,171.7,ohc,four,85.0,27.0,7975.0
82,volkswagen,sedan,NaN,171.7,NaN,four,52.0,37.0,7995.0
87,volvo,sedan,104.3,188.8,NaN,four,114.0,23.0,12940.0

In [ ]:
df.shape

(33, 9)

In [ ]:
df.head()

,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
index,,,,,,,,,
1,alfa-romero,convertible,NaN,168.8,dohc,four,111.0,21.0,16500.0
3,audi,sedan,99.8,176.6,ohc,four,102.0,24.0,13950.0
5,audi,sedan,99.8,177.3,ohc,five,110.0,19.0,15250.0
6,audi,wagon,105.8,192.7,ohc,five,110.0,19.0,18920.0
10,bmw,sedan,NaN,176.8,ohc,four,101.0,23.0,16925.0

.fillna()

In [25]:
df = pd.read_csv("https://github.com/anvarnarz/praktikum_datasets/raw/main/automobile_data_nan.csv", index_col=0)
df

,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
index,,,,,,,,,
0,alfa-romero,convertible,88.6,168.8,dohc,four,NaN,21.0,13495.0
1,alfa-romero,convertible,NaN,168.8,dohc,four,111.0,21.0,16500.0
2,alfa-romero,hatchback,94.5,171.2,ohcv,six,154.0,NaN,16500.0
3,audi,sedan,99.8,176.6,ohc,four,102.0,24.0,13950.0
4,audi,sedan,99.4,176.6,ohc,five,NaN,NaN,17450.0
...,...,...,...,...,...,...,...,...,...
81,volkswagen,sedan,97.3,171.7,ohc,four,85.0,27.0,7975.0
82,volkswagen,sedan,NaN,171.7,NaN,four,52.0,37.0,7995.0
86,volkswagen,sedan,97.3,NaN,ohc,four,100.0,NaN,9995.0
87,volvo,sedan,104.3,188.8,NaN,four,114.0,23.0,12940.0
88,volvo,wagon,104.3,188.8,ohc,four,NaN,23.0,13415.0

In [29]:
df.fillna(0)

,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
index,,,,,,,,,
0,alfa-romero,convertible,88.6,168.8,dohc,four,0.0,21.0,13495.0
1,alfa-romero,convertible,0.0,168.8,dohc,four,111.0,21.0,16500.0
2,alfa-romero,hatchback,94.5,171.2,ohcv,six,154.0,0.0,16500.0
3,audi,sedan,99.8,176.6,ohc,four,102.0,24.0,13950.0
4,audi,sedan,99.4,176.6,ohc,five,0.0,0.0,17450.0
...,...,...,...,...,...,...,...,...,...
81,volkswagen,sedan,97.3,171.7,ohc,four,85.0,27.0,7975.0
82,volkswagen,sedan,0.0,171.7,0,four,52.0,37.0,7995.0
86,volkswagen,sedan,97.3,0.0,ohc,four,100.0,0.0,9995.0
87,volvo,sedan,104.3,188.8,0,four,114.0,23.0,12940.0
88,volvo,wagon,104.3,188.8,ohc,four,0.0,23.0,13415.0

In [30]:
df.fillna(method='ffill')

,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
index,,,,,,,,,
0,alfa-romero,convertible,88.6,168.8,dohc,four,NaN,21.0,13495.0
1,alfa-romero,convertible,88.6,168.8,dohc,four,111.0,21.0,16500.0
2,alfa-romero,hatchback,94.5,171.2,ohcv,six,154.0,21.0,16500.0
3,audi,sedan,99.8,176.6,ohc,four,102.0,24.0,13950.0
4,audi,sedan,99.4,176.6,ohc,five,102.0,24.0,17450.0
...,...,...,...,...,...,...,...,...,...
81,volkswagen,sedan,97.3,171.7,ohc,four,85.0,27.0,7975.0
82,volkswagen,sedan,97.3,171.7,ohc,four,52.0,37.0,7995.0
86,volkswagen,sedan,97.3,171.7,ohc,four,100.0,37.0,9995.0
87,volvo,sedan,104.3,188.8,ohc,four,114.0,23.0,12940.0
88,volvo,wagon,104.3,188.8,ohc,four,114.0,23.0,13415.0

In [31]:
df.fillna(method='bfill')

,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
index,,,,,,,,,
0,alfa-romero,convertible,88.6,168.8,dohc,four,111.0,21.0,13495.0
1,alfa-romero,convertible,94.5,168.8,dohc,four,111.0,21.0,16500.0
2,alfa-romero,hatchback,94.5,171.2,ohcv,six,154.0,24.0,16500.0
3,audi,sedan,99.8,176.6,ohc,four,102.0,24.0,13950.0
4,audi,sedan,99.4,176.6,ohc,five,110.0,19.0,17450.0
...,...,...,...,...,...,...,...,...,...
81,volkswagen,sedan,97.3,171.7,ohc,four,85.0,27.0,7975.0
82,volkswagen,sedan,97.3,171.7,ohc,four,52.0,37.0,7995.0
86,volkswagen,sedan,97.3,188.8,ohc,four,100.0,23.0,9995.0
87,volvo,sedan,104.3,188.8,ohc,four,114.0,23.0,12940.0
88,volvo,wagon,104.3,188.8,ohc,four,NaN,23.0,13415.0

In [32]:
df.fillna({'wheel-base':90,'horsepower':100})

,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
index,,,,,,,,,
0,alfa-romero,convertible,88.6,168.8,dohc,four,100.0,21.0,13495.0
1,alfa-romero,convertible,90.0,168.8,dohc,four,111.0,21.0,16500.0
2,alfa-romero,hatchback,94.5,171.2,ohcv,six,154.0,NaN,16500.0
3,audi,sedan,99.8,176.6,ohc,four,102.0,24.0,13950.0
4,audi,sedan,99.4,176.6,ohc,five,100.0,NaN,17450.0
...,...,...,...,...,...,...,...,...,...
81,volkswagen,sedan,97.3,171.7,ohc,four,85.0,27.0,7975.0
82,volkswagen,sedan,90.0,171.7,NaN,four,52.0,37.0,7995.0
86,volkswagen,sedan,97.3,NaN,ohc,four,100.0,NaN,9995.0
87,volvo,sedan,104.3,188.8,NaN,four,114.0,23.0,12940.0
88,volvo,wagon,104.3,188.8,ohc,four,100.0,23.0,13415.0

In [36]:
df.fillna({'wheel-base':np.mean(df['wheel-base']),'horsepower':np.mean(df['horsepower'])}, inplace=True)

In [34]:
df.fillna(df.mean())

<ipython-input-34-a2478f315f9e>:1: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  df.fillna(df.mean())

,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
index,,,,,,,,,
0,alfa-romero,convertible,88.600000,168.800000,dohc,four,108.266667,21.000000,13495.0
1,alfa-romero,convertible,99.219565,168.800000,dohc,four,111.000000,21.000000,16500.0
2,alfa-romero,hatchback,94.500000,171.200000,ohcv,six,154.000000,25.695652,16500.0
3,audi,sedan,99.800000,176.600000,ohc,four,102.000000,24.000000,13950.0
4,audi,sedan,99.400000,176.600000,ohc,five,108.266667,25.695652,17450.0
...,...,...,...,...,...,...,...,...,...
81,volkswagen,sedan,97.300000,171.700000,ohc,four,85.000000,27.000000,7975.0
82,volkswagen,sedan,99.219565,171.700000,NaN,four,52.000000,37.000000,7995.0
86,volkswagen,sedan,97.300000,173.852083,ohc,four,100.000000,25.695652,9995.0
87,volvo,sedan,104.300000,188.800000,NaN,four,114.000000,23.000000,12940.0
88,volvo,wagon,104.300000,188.800000,ohc,four,108.266667,23.000000,13415.0

In [38]:
df[df.company=='toyota'].fillna(df[df.company=='toyota'].mean())

<ipython-input-38-6e60cd9f5a1c>:1: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  df[df.company=='toyota'].fillna(df[df.company=='toyota'].mean())

,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
index,,,,,,,,,
66,toyota,hatchback,99.219565,158.700000,ohc,four,62.000000,35.000000,5348.0
67,toyota,hatchback,95.700000,158.700000,NaN,four,108.266667,31.000000,6338.0
68,toyota,hatchback,99.219565,158.700000,ohc,four,62.000000,31.000000,6488.0
69,toyota,wagon,95.700000,169.700000,ohc,four,62.000000,31.000000,6918.0
70,toyota,wagon,95.700000,167.216667,NaN,four,62.000000,27.000000,7898.0
71,toyota,wagon,95.700000,169.700000,ohc,four,108.266667,27.000000,8778.0
79,toyota,wagon,104.500000,187.800000,dohc,six,156.000000,30.333333,15750.0